### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by MinhPT-99** [lam6670/lam6670.github.io#1]
![image](https://user-images.githubusercontent.com/49905389/66320104-6bfa6580-e948-11e9-9258-feda856c3312.png)
Học bao lâu rồi mà còn căn giữa thế này hả????? Sửa lại ngay!!! Chia ruộng sai luôn rồi.! Muốn ăn đòn hả? Hừmmmmmm

**Comment by lam6670** [comment]
Ơ thì em vẫn thấy nó lên thành hình :v

Vào 21:24, Th 2, 7 thg 10, 2019 Phan Tuấn Minh <notifications@github.com>
đã viết:

**Comment by minhpt99** [comment]
Thành hình mà sai tòe tòe ra thì ai thuê ô đi làm -_-
